version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/kafka/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  ingest_coingecko:
    build:
      context: ./services/ingest_coingecko
    container_name: ingest-coingecko
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "crypto_quotes_raw"
      POLL_SECONDS: "60"
      COINGECKO_BASE_URL: "https://api.coingecko.com/api/v3"
      VS_CURRENCY: "usd"
      ORDER: "market_cap_desc"
      PER_PAGE: "50"
      PAGE: "1"
      PRICE_CHANGE_PERCENTAGE: "24h"

  kafka-connect:
    build:
      context: ./services/connect
      dockerfile: Dockerfile
    container_name: kafka-connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"

      CONNECT_CONFIG_STORAGE_TOPIC: "_connect_configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_connect_offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_connect_status"

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

      # AWS credentials are read from env vars by the connector (we'll configure it)
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
    restart: on-failure

  spark:
    build:
      context: ./services/spark
    container_name: spark
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark master
    volumes:
      - ./services/spark_jobs:/opt/spark_jobs
    command: >
      bash -lc "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*"

  spark-worker:
    build:
      context: ./services/spark
    container_name: spark-worker
    depends_on:
      - spark
    env_file:
      - .env
    environment:
      SPARK_MASTER_URL: spark://spark:7077
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    command: >
      bash -lc "/opt/spark/sbin/start-worker.sh spark://spark:7077 && tail -f /opt/spark/logs/*"

  spark-silver:
    build:
      context: .
      dockerfile: services/spark/Dockerfile
    container_name: spark-silver
    depends_on:
      - spark
      - spark-worker
    env_file:
      - .env
    user: "0:0"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      BRONZE_PREFIX: "bronze/crypto_quotes_raw"
      SILVER_HISTORY_PREFIX: "silver/crypto_quotes_history"
      SILVER_LATEST_PREFIX: "silver/crypto_quotes_latest"
      SPARK_USER: spark
      SPARK_LOCAL_DIRS: /tmp/spark
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/ivy -Divy.home=/tmp/ivy"

    volumes:
      - ivy_cache:/tmp/ivy

    entrypoint: [ "/opt/spark/bin/spark-submit" ]
    command:
      - "--master"
      - "spark://spark:7077"
      - "--deploy-mode"
      - "client"
      - "--packages"
      - "org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
      - "/opt/spark_jobs/crypto_silver/bronze_to_silver.py"

  spark-gold:
    build:
      context: .
      dockerfile: services/spark/Dockerfile
    container_name: spark-gold
    depends_on:
      - spark
      - spark-worker
    env_file:
      - .env
    user: "0:0"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"

      # inputs
      SILVER_HISTORY_PREFIX: "silver/crypto_quotes_history"
      SILVER_LATEST_PREFIX: "silver/crypto_quotes_latest"

      # outputs
      GOLD_PREFIX: "gold"

      SPARK_USER: spark
      SPARK_LOCAL_DIRS: /tmp/spark
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/ivy -Divy.home=/tmp/ivy"
    volumes:
      - ivy_cache:/tmp/ivy
    entrypoint: [ "/opt/spark/bin/spark-submit" ]
    command:
      - "--master"
      - "spark://spark:7077"
      - "--deploy-mode"
      - "client"
      - "--packages"
      - "org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
      - "/opt/spark_jobs/crypto_gold/silver_to_gold.py"

  athena-apply:
    build:
      context: ./services/athena_apply
    container_name: athena-apply
    env_file:
      - .env
    environment:

      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"

      # Athena runner config (add these to .env)
      ATHENA_DATABASE: "${ATHENA_DATABASE}"
      ATHENA_WORKGROUP: "${ATHENA_WORKGROUP}"
      ATHENA_OUTPUT_S3: "${ATHENA_OUTPUT_S3}"

      # Where the SQL files live inside the container
      ATHENA_SQL_DIR: "${ATHENA_SQL_DIR}"

    volumes:
      - ./sql/athena:/sql/athena:ro

    # Run and exit (no long-running container)
    restart: "no"

  athena-repair:
    build:
      context: .
      dockerfile: services/athena_apply/Dockerfile

    container_name: athena-repair
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"

      ATHENA_DB_NAME: "${ATHENA_DATABASE}"
      ATHENA_WORKGROUP: "${ATHENA_WORKGROUP}"
      ATHENA_OUTPUT_S3: "${ATHENA_OUTPUT_S3}"

      # where SQL files live inside the container
      ATHENA_SQL_DIR: "${ATHENA_SQL_DIR}"

      # IMPORTANT: only run the repair SQL
      ATHENA_FILES: "99_repair_partitions.sql"


  airflow-postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    build:
      context: ./services/airflow
    container_name: airflow-init
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_UID: "50000"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname Daniel --role Admin --email admin@example.com || true"
  

  airflow-webserver:
    build:
      context: ./services/airflow
    container_name: airflow-webserver
    user: "0:0"
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    environment:
      DOCKER_API_VERSION: "1.43"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

      # Allow Airflow to run "docker compose run ..."
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/project:rw
    command: webserver

  airflow-scheduler:
    build:
      context: ./services/airflow
    container_name: airflow-scheduler
    user: "0:0"
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      DOCKER_API_VERSION: "1.43"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

      # Allow Airflow to run "docker compose run ..."
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/project:rw
    command: scheduler

volumes:
  kafka_data:
    name: crypto_kafka_data
  zookeeper_data:
    name: crypto_zookeeper_data
  zookeeper_datalog:
    name: crypto_zookeeper_datalog
  connect_data:
    name: crypto_connect_data
  ivy_cache:
    name: crypto_ivy_cache
  airflow_pgdata:
    name: crypto_airflow_pgdata
